# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 12:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('idCourt', models.AutoField(db_column=b'idCourt', primary_key=True, serialize=False, verbose_name=b'Pista')),
                ('name', models.CharField(db_column=b'name', default=b'', help_text=b'Solo letras, numeros y espacios.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_name', message=b'Solo letras, puntuacion y numeros, maximo 200.', regex=b'^([0-9a-zA-Z][, .:]*){1,200}$')], verbose_name=b'Nombre')),
                ('width', models.DecimalField(db_column=b'width', decimal_places=2, default=0.0, help_text=b'1 a 5 parte entera, 2 parte decimal.', max_digits=7, validators=[django.core.validators.RegexValidator(code=b'invalid_width', message=b'1 a 5 parte entera y 2 parte decimal.', regex=b'^(([0-9]{1,5}\\.[0-9]{1,2})|([0-9]{1,5}))$')], verbose_name=b'Ancho')),
                ('length', models.DecimalField(db_column=b'length', decimal_places=2, default=0.0, help_text=b'1 a 5 parte entera, 2 parte decimal.', max_digits=7, validators=[django.core.validators.RegexValidator(code=b'invalid_length', message=b'1 a 5 parte entera y 2 parte decimal.', regex=b'^(([0-9]{1,5}\\.[0-9]{1,2})|([0-9]{1,5}))$')], verbose_name=b'Largo')),
                ('avaible', models.CharField(db_column=b'avaible', max_length=2, validators=[django.core.validators.RegexValidator(code=b'invalid_avaible', message=b'Solo Si o No.', regex=b'^(Si|No)$')], verbose_name=b'Disponible')),
                ('description', models.TextField(db_column=b'description', default=b'', help_text=b'Solo letras, numeros y espacios.', validators=[django.core.validators.RegexValidator(code=b'invalid_description', message=b'Solo letras, puntuacion y numeros, maximo 500.', regex=b'^([0-9a-zA-Z][, .:]*){1,500}$')], verbose_name=b'Descripcion')),
                ('image', models.ImageField(db_column=b'image', help_text=b'jpg,bmp,svg o png.', upload_to=b'court/', verbose_name=b'Imagen')),
                ('price', models.DecimalField(db_column=b'price', decimal_places=2, default=0.0, help_text=b'1 a 3 parte entera, 2 parte decimal.', max_digits=5, validators=[django.core.validators.RegexValidator(code=b'invalid_price', message=b'1 a 3 parte entera y 2 parte decimal.', regex=b'^(([0-9]{1,3}\\.[0-9]{1,2})|([0-9]{1,3}))$')], verbose_name=b'Precio')),
            ],
            options={
                'db_table': 'Court',
                'verbose_name': 'Pista',
                'verbose_name_plural': 'Pistas',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idReservation', models.AutoField(db_column=b'idReservation', primary_key=True, serialize=False, verbose_name=b'Reserva')),
                ('date', models.CharField(db_column=b'date', default=b'2016-06-10', help_text=b'aaaa-mm-dd.', max_length=10, validators=[django.core.validators.RegexValidator(code=b'invalid_date', message=b'aaaa-mm-dd.', regex=b'^([2-9][0-9]{3})\\-(0[1-9]|1[0-2])\\-(0[1-9]|[1|2][0-9]|[3][0|1])$')], verbose_name=b'Fecha')),
                ('hour', models.CharField(db_column=b'hour', default=b'09:00', help_text=b'09:00 a 20:00 horas exactas.', max_length=5, validators=[django.core.validators.RegexValidator(code=b'invalid_hour', message=b'de 09:00 a 20:00, horas exactas.', regex=b'^((09|1[0-9]|20):00)$')], verbose_name=b'Hora')),
                ('duration', models.CharField(db_column=b'duration', default=b'01:00', help_text=b'01-09 horas:00.', max_length=5, validators=[django.core.validators.RegexValidator(code=b'invalid_duration', message=b'hh:mm,mm = 01:00-09:00 min 01:00 max 09:00 horas.', regex=b'^(0[1-9]):00$')], verbose_name=b'Duracion')),
                ('cost', models.DecimalField(db_column=b'cost', decimal_places=2, default=0.0, help_text=b'1 a 8 parte entera, 2 parte decimal.', max_digits=10, validators=[django.core.validators.RegexValidator(code=b'invalid_cost', message=b'1 a 8 parte entera y 2 parte decimal.', regex=b'^(([0-9]{1,8}\\.[0-9]{1,2})|([0-9]{1,8}))$')], verbose_name=b'Coste')),
                ('court', models.ForeignKey(db_column=b'court', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_court', to='court.Court', verbose_name=b'Pista')),
                ('user', models.ForeignKey(db_column=b'user', on_delete=django.db.models.deletion.CASCADE, related_name='reservation_user', to=settings.AUTH_USER_MODEL, verbose_name=b'Usuario')),
            ],
            options={
                'db_table': 'Reservation',
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
