# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 21:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('idExercise', models.AutoField(db_column=b'idExercise', primary_key=True, serialize=False, verbose_name=b'Ejercicio')),
                ('name', models.CharField(db_column=b'name', default=b'', help_text=b'Solo letras, numeros y espacios.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_name', message=b'Solo letras, puntuacion y numeros, maximo 200.', regex=b'^([0-9a-zA-Z][, .:]*){1,200}$')], verbose_name=b'Nombre')),
                ('image', models.ImageField(db_column=b'image', help_text=b'jpg,bmp,svg o png.', upload_to=b'exercise/', verbose_name=b'Imagen')),
                ('zone', models.CharField(choices=[(b'Pecho', b'Pecho'), (b'Espalda', b'Espalda'), (b'Brazos', b'Brazos'), (b'Piernas', b'Piernas')], db_column=b'zone', default=b'Pecho', max_length=100, verbose_name=b'Zona')),
            ],
            options={
                'db_table': 'Exercise',
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('idMachine', models.AutoField(db_column=b'idMachine', primary_key=True, serialize=False, verbose_name=b'Maquina')),
                ('name', models.CharField(db_column=b'name', default=b'', help_text=b'Solo letras, numeros y espacios.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_name', message=b'Solo letras, puntuacion y numeros, maximo 200.', regex=b'^([0-9a-zA-Z][, .:]*){1,200}$')], verbose_name=b'Nombre')),
                ('description', models.TextField(db_column=b'description', default=b'', help_text=b'Solo letras, numeros y espacios.', validators=[django.core.validators.RegexValidator(code=b'invalid_description', message=b'Solo letras, puntuacion y numeros, maximo 500.', regex=b'^([0-9a-zA-Z][, .:]*){1,500}$')], verbose_name=b'Descripcion')),
                ('image', models.ImageField(db_column=b'image', help_text=b'jpg,bmp,svg o png.', upload_to=b'machine/', verbose_name=b'Imagen')),
                ('quantity', models.CharField(db_column=b'quantity', default=1, help_text=b'Minimo 1, maximo 99.', max_length=2, validators=[django.core.validators.RegexValidator(code=b'invalid_quantity', message=b'Entre 1 y 99.', regex=b'^([1-9]{1,1}|[1-9]{1,1}[0-9]{1,1})$')], verbose_name=b'Cantidad')),
            ],
            options={
                'db_table': 'Machine',
                'verbose_name': 'Maquina',
                'verbose_name_plural': 'Maquinas',
            },
        ),
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('idPlanification', models.AutoField(db_column=b'idPlanification', primary_key=True, serialize=False, verbose_name=b'Planificacion')),
                ('name', models.CharField(db_column=b'name', default=b'', help_text=b'Solo letras, numeros y espacios.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_name', message=b'Solo letras, puntuacion y numeros, maximo 200.', regex=b'^([0-9a-zA-Z][, .:]*){1,200}$')], verbose_name=b'Nombre')),
                ('day', models.CharField(choices=[(b'Lunes', b'Lunes'), (b'Martes', b'Martes'), (b'Miercoles', b'Miercoles'), (b'Jueves', b'Jueves'), (b'Viernes', b'Viernes')], db_column=b'day', default=b'Lunes', max_length=100, verbose_name=b'Dia')),
            ],
            options={
                'db_table': 'Planification',
                'verbose_name': 'Planificacion',
                'verbose_name_plural': 'Planificaciones',
            },
        ),
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('idProgramm', models.AutoField(db_column=b'idReservation', primary_key=True, serialize=False, verbose_name=b'Reserva')),
                ('name', models.CharField(db_column=b'name', default=b'', help_text=b'Solo letras, numeros y espacios.', max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code=b'invalid_name', message=b'Solo letras, puntuacion y numeros, maximo 200.', regex=b'^([0-9a-zA-Z][, .:]*){1,200}$')], verbose_name=b'Nombre')),
                ('quantity', models.CharField(db_column=b'quantity', default=1, help_text=b'Minimo 1, maximo 99.', max_length=2, validators=[django.core.validators.RegexValidator(code=b'invalid_quantity', message=b'Entre 1 y 99.', regex=b'^([1-9]{1,1}|[1-9]{1,1}[0-9]{1,1})$')], verbose_name=b'Cantidad')),
                ('series', models.CharField(db_column=b'series', default=1, help_text=b'Minimo 1, maximo 15.', max_length=2, validators=[django.core.validators.RegexValidator(code=b'invalid_series', message=b'Entre 1 y 15.', regex=b'^([1-9]{1,1}|[1][0-5]{1,1})$')], verbose_name=b'Series')),
                ('rest', models.CharField(db_column=b'rest', default=1, help_text=b'Minimo 1, maximo 15.', max_length=2, validators=[django.core.validators.RegexValidator(code=b'invalid_rest', message=b'Entre 0 y 15.', regex=b'^([1-9]{1,1}|[1][0-5]{1,1})$')], verbose_name=b'Descanso')),
                ('exercise', models.ForeignKey(db_column=b'exercise', on_delete=django.db.models.deletion.CASCADE, related_name='programm_exercise', to='machine.Exercise', verbose_name=b'Ejercicio')),
            ],
            options={
                'db_table': 'Programm',
                'verbose_name': 'Programa',
                'verbose_name_plural': 'Programas',
            },
        ),
        migrations.AddField(
            model_name='planification',
            name='programm',
            field=models.ForeignKey(db_column=b'programm', on_delete=django.db.models.deletion.CASCADE, related_name='planification_programm', to='machine.Programm', verbose_name=b'Programa'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='machine',
            field=models.ForeignKey(db_column=b'machine', on_delete=django.db.models.deletion.CASCADE, related_name='exercise_machine', to='machine.Machine', verbose_name=b'Maquina'),
        ),
    ]
