"""
Django settings for sportcenter project.

Generated by 'django-admin startproject' using Django 1.8.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

 
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jyp6cg-202vct4buphwy)m54f#z9nuz6g!p=rzim0q447_i2@h'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

DJANGO_APPS = (
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',
#'django.contrib.sites',
)

THIRD_PARTY_APPS = (
'debug_toolbar', 
'widget_tweaks',
'carton',
)

LOCAL_APPS = (
'court',
'machine',
'product',
'userapp',
'main',
'classroom',
)

INSTALLED_APPS = DJANGO_APPS + THIRD_PARTY_APPS +  LOCAL_APPS 

MIDDLEWARE_CLASSES = (
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'sportcenter.urls'

from unipath import Path

RUTA_PROYECTO = Path(__file__).ancestor(2)

TEMPLATE_PATH = RUTA_PROYECTO.child('templates')

# import os 

#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#TEMPLATE_PATH = os.path.join(BASE_DIR,'templates')

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sportcenter.wsgi.application'


STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

#STATIC_PATH = os.path.join(BASE_DIR, 'static')

STATIC_PATH = RUTA_PROYECTO.child('static')

#MEDIA_PATH = os.path.join(BASE_DIR,'media')

MEDIA_PATH = RUTA_PROYECTO.child('media')

STATICFILES_DIRS = (
   STATIC_PATH, 
)

#MEDIA_ROOT = RUTA_PROYECTO.child('media')

MEDIA_ROOT = MEDIA_PATH

AUTH_PROFILE_MODULE = 'userapp.UserApp'

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DEBUG = True

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'sportcenter',
        'HOST':'',
        'PASSWORD':'root',
        'USER':'root',
        'PORT':3306,
    }
}

import sys

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(asctime)s] %(levelname)s [%(name)s:%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'depuracion_sportcenter.log',
            'formatter': 'verbose'
        },
        'console': {
            'class': 'logging.StreamHandler',
            'stream': sys.stdout,
        },
    },
    'loggers': {
        'sportcenter.page_processors': {
            'handlers': ['console','file'],
            'level': 'DEBUG',
        }
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/


USE_I18N = True

USE_L10N = True

USE_TZ = True

LANGUAGE_CODE = 'es-ES'

TIME_ZONE = 'Europe/Madrid'

MEDIA_URL = '/media/'

LOGIN_URL = '/sportcenter/login/'

LOGOUT_URL = '/sportcenter/logout/'

LOGIN_REDIRECT_URL = '/sportcenter/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#FILE_UPLOAD_HANDLERS = ('uploadprogresscachedhandler.UploadProgressCachedHandler', ) \
#+ global_settings.FILE_UPLOAD_HANDLERS

CART_PRODUCT_MODEL='product.models.Product'
